Do not skip messaages in integration tests (#1109)
I believe this fixes
https://github.com/clojure-lsp/clojure-lsp/issues/704.

I noticed something curious while watching the integration tests run.

In addition to the regular client logs and the server logs, I had the
lower-level trace logs that lsp4j provides turned on. These traces say
what messages lsp4j thinks it's sending.

The log output looked like this:

```
client log: sent request
client log: received notification 1
client log: received notification 2

error: client timed out waiting for server's response to request

server log: sending notification 1
server log: finished generating response to client request
server log: sending notification 2

server trace: received request
server trace: sent notification 1
server trace: sent response
server trace: sent notification 2
```

First notice that the server log and server trace agree:

1. server received request (the server logs don't include message
   receipts, but we can assume it happened).
2. server sent notification (a diagnostics notification, though it
   doesn't matter)
3. server sent response (after it finished generating it)
4. server sent notification (diagnostics again)

But the client saw something else. It received both notifications, but
failed to receive the response that was in between them.

How could that be? Both sides were able to communicate the second
notification, so there can't be anything wrong with the i/o streams. It
appears that the client listener just ignored the server's response. And
with a little research, that's exactly what happened.

Let's look at the messages a little more. Ignoring some details about
line endings, the messages look like this:

```
Content-Length: 8

{"a": 1}
```

In the integration tests we read and discard the Content-Length line,
then ask cheshire to parse the JSON object, which it returns. Normally
this works OK, but remember that we actually have a message stream, so
sometimes it contains two messages:

```
Content-Length: 8

{"a": 1}
Content-Length: 8

{"b": 2}
```

It turns out that `cheshire/parse-stream` will consume the first JSON
object. But if there is additional text after that JSON object, it *will
consume that too*. It returns the first JSON object, but reads past
anything else that was in the stream.

What this means is that whenever there are two or more messages in the
stream, cheshire will skip all but the first. And if the tests assert
that a skipped message should be delivered, the tests freeze and then,
after a timeout, fail.

I tried out a few different libs to see how they behave.

clojure.data.json/read and charred.core/read-json exhibit the same
behavior. They read and parse an object then read to the end of the
stream. cheshire.core/parse-string can't work on a stream, but on
strings it does the same thing—reads one object, then ignores the rest
of the string.

The only tool that looked promising is charred.core/read-json-supplier.
If the stream contains two JSON objects, you can call `(.get supplier)`
twice and get both objects. But if there's other stuff in between the
objects, like Content-Length headers, `.get` throws an exception.

There may be a library that will do what we want, but rather than
continue looking I decided to do it myself—I took control of how the
stream is consumed. Now the code starts a listener loop that reads the
Content-Length header. It uses the value in the header to decide how
many characters the message will be. It reads that many characters off
the stream, and puts them into a string. Then it asks cheshire to parse
the string. After cheshire is done, it processes the message and recurs.
We never read more than one message at a time, so no messages are
skipped.

The last thing I feel like I don't fully understand is why this wasn't
happening more. The criteria for the bug are a bit rare, but not
terribly uncommon. Two messages have to be sent at nearly the same time
(this is why the logs so often contain diagnostics notifications around
the failure—diagnostics are sent asynchronously and so are more likely
to overlap with the regular responses) and the test assertion has to be
about the second message. Maybe the client code was so fast (it doesn't
do much) that it was rare for two messages to stack up.

In any case, as is always true when reducing flakines, I think this will
help but I can't be sure it's the only problem. We'll see!